spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
  application:
    name: orderitem
  datasource:
    url: jdbc:mysql://192.168.1.107:3306/goods?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
server:
  port: 6000